spring:
    application:
        name: config-center
    cloud:
        bus:
            trace:
                enabled: true
        config:
            server:
                git:
                    uri: ${CI_GIT_URL:https://github.com/zihang5127/cloud-platform-config-repo.git}
                    clone-on-start: ${CLONE_ON_START:true}
                    search-paths: services/**


server:
    port: 9010

eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${REGISTRY_CENTER_URI:http://localhost:9020/eureka/}

security:
    basic:
        enabled: false
    user:
        name: user
        password: 123456